# This file is auto-generated by LitServe.
# Disable auto-generation by setting `generate_client_file=False` in `LitServer.run()`.

import requests

response = requests.post(
    "http://127.0.0.1:8082/predict",
    json={
        "image_url": "img_url",
        # "polygon_mask":[[[],[],[]],]
        "rotation":"ROTATE_90_CLOCKWISE"
    },
)
print(f"Status: {response.status_code}\nResponse:\n {response.json()}")

# {
#     "predict": [
#         [
#             {
#                 "name": "person",
#                 "class": 0,
#                 "confidence": 0.91672,
#                 "box": {
#                     "x1": 863.12262,
#                     "y1": 11.8943,
#                     "x2": 1043.15515,
#                     "y2": 618.11456,
#                 },
#             },
#             {
#                 "name": "person",
#                 "class": 0,
#                 "confidence": 0.89414,
#                 "box": {
#                     "x1": 451.05511,
#                     "y1": 74.21596,
#                     "x2": 589.74786,
#                     "y2": 609.77185,
#                 },
#             },
#             {
#                 "name": "person",
#                 "class": 0,
#                 "confidence": 0.89322,
#                 "box": {
#                     "x1": 307.9744,
#                     "y1": 96.92538,
#                     "x2": 458.71964,
#                     "y2": 596.19574,
#                 },
#             },
#             {
#                 "name": "person",
#                 "class": 0,
#                 "confidence": 0.88899,
#                 "box": {
#                     "x1": 153.09256,
#                     "y1": 74.24045,
#                     "x2": 321.052,
#                     "y2": 599.03979,
#                 },
#             },
#             {
#                 "name": "person",
#                 "class": 0,
#                 "confidence": 0.86645,
#                 "box": {
#                     "x1": 536.32074,
#                     "y1": 26.08372,
#                     "x2": 744.08893,
#                     "y2": 618.94891,
#                 },
#             },
#             {
#                 "name": "person",
#                 "class": 0,
#                 "confidence": 0.857,
#                 "box": {
#                     "x1": 738.1275,
#                     "y1": 79.15552,
#                     "x2": 863.89441,
#                     "y2": 594.43573,
#                 },
#             },
#         ]
#     ]
# }
