FROM python:3.12-slim

WORKDIR /workspace

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libgomp1 \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY service.py .
COPY age_gender_yolo.pt .
ENV YOLO_CONFIG_DIR=/workspace/Ultralytics

CMD ["python", "service.py"]
