FROM python:3.12-slim

WORKDIR /workspace

RUN apt-get update
RUN pip install minio==7.2.20 redis==7.1.0

COPY delete.py /workspace/delete.py
COPY settings.py /workspace/settings.py

CMD ["python", "delete.py"]